---
title: "Grasshopper"
author: "Mohammad Inam Jameel"
date: '2022-11-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Desktop/Anderson_data/herbivory/data/field/grasshopper/")
```

```{r, echo=FALSE}
#libraries
library(dplyr)
library(ggplot2)
library(nlme)
library(lme4)
library(tidyr)
library(broom)
library(car)
library(MASS)
library(emmeans)
library(visreg)
library(gamlss)
library(effects)
library(mgcv)
library(glmmTMB)
library(bbmle)

#read in data 
grasshopper <- read.csv("Grasshopper_data.csv")

sapply(grasshopper,class)
##Some  variables are being read as characters not factors. Let's fix that
grasshopper$Genotype<-as.factor(grasshopper$Genotype)
grasshopper$population<-as.factor(grasshopper$population)
grasshopper$Treatment<-as.factor(grasshopper$Treatment)
grasshopper$Block<-as.factor(grasshopper$Block)
grasshopper$Herbivore<-as.factor(grasshopper$Herbivore)
grasshopper$Cage<-as.factor(grasshopper$Cage)
grasshopper$Exclude_2022<-as.factor(grasshopper$Exclude_2022)

##Change the baseline for treatment
grasshopper $Treatment <-factor(grasshopper $Treatment, levels = c("watered", "Control"))


##This standardizes source elevation to a mean of 0 and standard deviation of 1, which is often necessary for model convergence
grasshopper $S_elev<-scale(grasshopper $elevation,center=TRUE, scale=TRUE)

##This standardizes initial plant size (measured as diameter in mm)  to a mean of 0 and standard deviation of 1 for use as a covariate in fitness models
grasshopper $S_initdiam<-scale(grasshopper $init.diam,center=TRUE, scale=TRUE)


#This rescales source elevation from meters to km
grasshopper$elev_km<-grasshopper $elevation/1000

#Let's concatenate cage and block to reduce nesting necessary for random effects.
grasshopper $block<-interaction(grasshopper$Cage, grasshopper$Block,sep = "_")

#Let's concatenate herbivore and watering treatments, which is helpful for some models.
grasshopper $treat<-interaction(grasshopper$Herbivore, grasshopper$Treatment,sep = "_")

#removing the individuals that were censor
grasshopper <- filter(grasshopper, Exclude_2022 == "Include")

```

##Analysis 1: Fitness##


```{r}
g_lar= ggplot(grasshopper, aes(x= elev,y= S1_LAR3, group= mat_treat, 
                               colour= mat_treat))+geom_point(size=5) + scale_y_continuous("Leaf Area Herbivorized",limits =c(0, 1))+ scale_x_continuous("Source Elevation")  
g_lar + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(),
                           panel.grid.minor=element_blank(),legend.position = "top")+geom_smooth(method="lm",size=1.6, formula=y~x)+facet_wrap(~ mat_treat, scales="free_x")# +scale_colour_manual(values = c( "lightblue","darkred"), name = "Watering treatment", labels = c("Ample water","Water-restricted"))


h_lar= ggplot(grasshopper1, aes(x= LAR_census6,y= Mature_length_siliques_2022, group= Treatment, 
                               colour= Treatment))+geom_point(size=5) + scale_y_continuous("Fitness",limits =c(0, 1500))+ scale_x_continuous("Leaf Area Herbivorized")  
h_lar + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(),
                           panel.grid.minor=element_blank(),legend.position = "top")+geom_smooth(method="lm",size=1.6, formula=y~x)+facet_wrap(~ Herbivore, scales="free_x") +scale_colour_manual(values = c( "lightblue","darkred"), name = "Watering treatment", labels = c("Ample water","Water-restricted"))



```




```{r}
#Probability of reproduction
logistic_model<-glmer(Reproduction_2022 ~ S_initdiam + elev_km* Herbivore* Treatment+ (1|block) +(1|population), data= grasshopper, family=binomial(link=logit), control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e7)))
  Anova(logistic_model , type="III")
  
## There is some indication of a treatment effect and a treatment by source elevation effect, but the p-values are marginal, and the patterns are opposite of predictions. (Trend for increasing probability of reproduction with source elevation under dry conditions, and decreasing prob. of repro. with source elevation under water conditions)
 ##Plotting the relationship between the probability of reproduction and source elevation under different environments.

 logmod <-predictorEffect("elev_km",  partial.residuals=TRUE, logistic_model)
  plot(logmod, lwd=2,xlab="Source elevation (km)", ylab="Probability of reproduction", pch=19, type="response",lines=list(multiline=TRUE, lty=2:1, col="black"),
       partial.residuals=list(smooth=FALSE, pch=19, col="black"), ylim=c(0,1.0))
  
```

```{r}
#Fruit Length
fecund<- glmer(Mature_length_siliques_2022 ~  S_initdiam +elev_km* Herbivore* Treatment+ (1|block) +(1|population), data= filter(grasshopper, Reproduction_2022 == 1),family=Gamma(link=log), control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e7)))
Anova(fecund,type="III")

fecundmod <-predictorEffect("elev_km",  partial.residuals=TRUE, fecund)
  plot(fecundmod, lwd=2,xlab="Source elevation (km)", ylab="Fecundity (number of silique)", pch=19, type="response",lines=list(multiline=FALSE, lty=2:1, col="black"),
       partial.residuals=list(smooth=FALSE, pch=19, col="black"), ylim=c(0,1500))

  #using concatenated water and herb treatment  
fecundB<- glmer(Mature_length_siliques_2022 ~  S_initdiam +elev_km* treat+ (1|block) +(1|population), data= filter(grasshopper, Reproduction_2022 == 1),family=Gamma(link=log), control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e7)))
Anova(fecundB,type="III")

fecundmodB <-predictorEffect("elev_km",  partial.residuals=TRUE, fecundB)
plot(fecundmodB, lwd=2,xlab="Source elevation (km)", ylab="Fecundity (Length of silique)", pch=19, type="response",lines=list(multiline=FALSE, lty=2:1, col="black"),
     partial.residuals=list(smooth=FALSE, pch=19, col="black"), ylim=c(0,1500))

```


```{r}
#Fruit number
fecundC<- glmer(Mature_silique_number_2022 ~  S_initdiam +elev_km* Herbivore* Treatment+ (1|block) +(1|population), data= filter(grasshopper, Reproduction_2022 == 1),family=Gamma(link=log), control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e7)))
Anova(fecundC,type="III")

fecundmodC <-predictorEffect("elev_km",  partial.residuals=TRUE, fecundC)
  plot(fecundmodC, lwd=2,xlab="Source elevation (km)", ylab="Fecundity (number of silique)", pch=19, type="response",lines=list(multiline=FALSE, lty=2:1, col="black"),
       partial.residuals=list(smooth=FALSE, pch=19, col="black"), ylim=c(0,100))
  
fecundD<- glmer(Mature_silique_number_2022 ~  S_initdiam +elev_km* treat+ (1|block) +(1|population), data= filter(grasshopper, Reproduction_2022 == 1),family=Gamma(link=log), control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e7)))
Anova(fecundD,type="III")

fecundmodD <-predictorEffect("elev_km",  partial.residuals=TRUE, fecundD)
plot(fecundmodD, lwd=2,xlab="Source elevation (km)", ylab="Fecundity (number of silique)", pch=19, type="response",lines=list(multiline=FALSE, lty=2:1, col="black"),
     partial.residuals=list(smooth=FALSE, pch=19, col="black"), ylim=c(0,100))

```



Analysis 1c: We can also do a hurdle model in one step in the glmmTMB package. First, we'll check a couple of diferent distributions. Running all of these models takes a while

```{r, echo=FALSE}
hurdle_Model = glmmTMB (round(Mature_length_siliques_2022) ~ S_initdiam +elev_km* Herbivore* Treatment + (1|block)+ (1| population), zi=~ S_initdiam +elev_km* Herbivore* Treatment  + (1|block)+ (1| population),data = grasshopper ,family=truncated_nbinom2)

fit_hnbinom1 = glmmTMB (round(Mature_length_siliques_2022) ~ S_initdiam +elev_km* Herbivore* Treatment + (1|block)+ (1| population), zi=~ S_initdiam +elev_km* Herbivore* Treatment  + (1|block)+ (1| population),data = grasshopper ,family=truncated_nbinom1)

#fit_trunc_poisson = glmmTMB (round(Mature_length_siliques_2022) ~ S_initdiam +elev_km* Herbivore* Treatment + (1|block)+ (1| population), zi=~ S_initdiam +elev_km* Herbivore* Treatment  + (1|block)+ (1| population),data = grasshopper ,family=truncated_poisson)

#fit_ziGamma = glmmTMB (round(Mature_length_siliques_2022) ~ S_initdiam +elev_km* Herbivore* Treatment + (1|block)+ (1| population), zi=~ S_initdiam +elev_km* Herbivore* Treatment  + (1|block)+ (1| population),data = grasshopper ,family=ziGamma) #model has NA/NaN function evaluation warning loop


#AICtab(hurdle_Model, fit_hnbinom1, fit_trunc_poisson, fit_ziGamma) #hurdle is best
```

```{r}
##This is the ANOVA table for the logistic regression part (probability of reproduction). It shows marginally signifciant source elevation by treatment interaction, similar to Analysis 1a.
Anova(hurdle_Model,type="III", component="zi")
##This is the ANOVA table for the count part (fecundity amongst individuals that reproduced). no sig.
Anova(hurdle_Model,type="III", component="cond")

fruit <-predictorEffect("elev_km",  partial.residuals=TRUE, hurdle_Model,component="cond")

plot(fruit, lwd=2,xlab="Source Elevation (KM)", ylab="Fruit", pch=19, type="response",lines=list(multiline=FALSE, lty=2:1, col="black"), partial.residuals=list(smooth=FALSE, pch=19, col="black"), ylim=c(0,1000))

```

```{r}
##Analysis 1d: We can also do a hurdle model in one step in the glmmTMB package. First, we'll check a couple of diferent distributions. Running all of these models takes a while
model_poisson <- glmmTMB(round(Mature_length_siliques_2022) ~S_initdiam +elev_km* Herbivore* Treatment + (1|block)+ (1| population), data=grasshopper, ziformula = ~1, family = poisson)


model_nb2 <- glmmTMB(round(Mature_length_siliques_2022) ~ S_initdiam +elev_km* Herbivore* Treatment + (1|block)+ (1| population), data=grasshopper,  ziformula = ~1, family = nbinom2)

model_nb1 <- glmmTMB(round(Mature_length_siliques_2022) ~ S_initdiam +elev_km* Herbivore* Treatment + (1|block)+ (1| population), data=grasshopper,  ziformula = ~1, family = nbinom1)

AICtab(model_nb2, model_nb1, model_poisson)

Anova(model_nb2,type="III")

  zeroinflated <-predictorEffect("elev_km",  partial.residuals=TRUE, model_nb2)
  plot(zeroinflated, lwd=2,xlab="Source elevation (km)", ylab="Fecundity", pch=19, type="response",lines=list(multiline=FALSE, lty=2:1, col="black"),
       partial.residuals=list(smooth=FALSE, pch=19, col="black"), ylim=c(0,1500))
```




#Analysis 2: Leaf damage #
```{r, echo= FALSE}

##In these analyses, we find that leaf damage increases with source elevation (as expected) more in the grasshopper treatment than the control.

##Analysis of leaf damage (LAR = leaf area removed) as a function of source elevation by watering treament by grasshopper treatment. We are going to use leaf damage data from the most recent census. Utimately, we will do a repeated measures analysis, but not right now.
grasshopper1 <- drop_na(grasshopper,LAR_census14_2022) 

         
##convert LAR (measured as % of leaf area removed by herbivores) to proportion
grasshopper1 $LAR_prop14<- grasshopper1 $LAR_census14_2022/100
      ##Check that the conversion worked
       hist(grasshopper1 $LAR_prop14)
head(grasshopper1)  
sapply(grasshopper1,class)    


#Let's concatenate water and herbivore treatment so that we can visualize all treatment levels in the same visreg model.
      grasshopper1 $treat_herb<-interaction(grasshopper1 $Treatment, grasshopper1 $Herbivore,sep = "_")
 
head(grasshopper1)
```

```{r}
#First, we will use ggplot to look at the data:

LAR_prop14 = ggplot(grasshopper1, aes(x= elevation,y=LAR_prop14, group= treat_herb))+geom_point(aes(colour= treat_herb ),size=5) +scale_x_continuous("elevation")+ scale_y_continuous("LAR_prop14")
LAR_prop14 + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(), 
                           panel.grid.minor=element_blank())+geom_smooth(aes(colour=treat_herb), method="glm",size=1.6)



LAR_prop143<-ggplot(grasshopper1, aes(x = Herbivore, y = LAR_prop14, fill = Treatment)) +
  geom_boxplot(outlier.shape = NA) +xlab("Herbivore treatment")+ scale_y_continuous("Leaf area removed (%)") +
  geom_point(pch = 21, position = position_jitterdodge())
LAR_prop143 + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(), 
                           panel.grid.minor=element_blank(),legend.position = "bottom")
                           
  
  
  LAR_prop143<-ggplot(grasshopper1, aes(x = Herbivore, y = LAR_prop14, fill = Treatment,)) +
  geom_boxplot(outlier.shape = NA) +xlab("Herbivore treatment")+ scale_y_continuous("Leaf area removed (%)") +
  geom_point(pch = 21, position = position_jitterdodge())
LAR_prop143 + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(), 
                           panel.grid.minor=element_blank(),legend.position = "top")+ scale_x_discrete(labels=c("grasshopper exclosure", "grasshopper enclosure")) +  scale_fill_manual(values = c( "lightblue","darkred"), name = "Watering treatment", labels = c("Ample water","Water-restricted"))

h_lar= ggplot(grasshopper1, aes(x= elev_km,y= LAR_prop14, group= Treatment, 
                               colour= Treatment))+geom_point(size=5) + scale_y_continuous("Leaf Area Herbivorized",limits =c(0, 0.30))+ scale_x_continuous("Source Elevation")  
h_lar + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(),
                           panel.grid.minor=element_blank(),legend.position = "top")+geom_smooth(method="lm",size=1.6, formula=y~x)+facet_wrap(~ Herbivore, scales="free_x") +scale_colour_manual(values = c( "lightblue","darkred"), name = "Watering treatment", labels = c("Ample water","Water-restricted"))
  


```

```{r}
#Let's concatenate cage and Block so that we don't have to worry about nesting 
      grasshopper1 $cage_block<-interaction(grasshopper1 $Cage, grasshopper1 $Block,sep = "_")
            grasshopper1 $trtherb<-interaction(grasshopper1 $Treatment, grasshopper1 $Herbivore,sep = "_")
            
            
              modA<- lmer (LAR_prop14~ Treatment*Herbivore*elev_km+S_initdiam+ (1|cage_block)+(1|Genotype),data= grasshopper1)


##Now, we will do a basic lmer model. This frameowrk isn't great for proportional data, but it's the most straightforward approach. 

    modA<- lmer (LAR_prop14~ Treatment+Herbivore*elev_km+ (1|cage_block)+(1|Genotype),data= grasshopper1)
 Anova(modA,type="III")
 ##You can see here that the residuals aren't great
 plot(modA)
 
 #Despite the heteroscedasticity in the residuals, hte plot here pretty much demonstrates the major patterns
  visreg(modA, overlay = TRUE, "elev_km", by="Herbivore", type="conditional", #scale = "response", 
       xlab="Source elevation (km)", ylab="Leaf damage from insect herbivores (proportion)", partial=TRUE,
       fill=list(col="light grey"
                 #(c(0.99), alpha=0)
       ), band = FALSE,
       #line=list(col=grey(c(0.2,0.6))),
       points=list(cex=0.65,  pch=(19)))
       

##This model allows us to visualize all treatments on the same figure
 modB <- lmer (LAR_prop14~trtherb*elev_km+ (1|cage_block)+(1|Genotype),data= grasshopper1)
 Anova(modB,type="III")
   visreg(modB, overlay = FALSE, "elev_km", by="trtherb", type="conditional", #scale = "response", 
       xlab="Source elevation (km)", ylab="Leaf damage from insect herbivores (proportion)", partial=TRUE,
       fill=list(col="light grey"
                 #(c(0.99), alpha=0)
       ), band = FALSE,
       #line=list(col=grey(c(0.2,0.6))),
       points=list(cex=0.65,  pch=(19)))
   

LAR <-predictorEffect("elev_km",  partial.residuals=TRUE, modA)
plot(LAR, lwd=2,xlab="Source Elevation (Km)", ylab="Leaf area removed by herbivores", pch=19, type="response",lines=list(multiline=FALSE, lty=2:1, col="black"), 
     partial.residuals=list(smooth=TRUE, pch=19, col="black"), ylim=c(0,0.3))

```

```{r}


##Now to get LSMEANS
modB<- lmer (LAR_prop14~Treatment*Herbivore*Genotype+ S_initdiam+ (1|cage_block)+(1|Genotype),data= grasshopper1)


fam_avg_linear<-emmeans(modB, ~Genotype:Treatment:Herbivore)
fam_means_linear<-as.data.frame(fam_avg_linear)

elev <- grasshopper1[c("Genotype","elevation")] #make dataframe of genotypes and corresponding elev
elev <- unique(elev) #calls unique rows 
LSmeans_LAR <- merge(fam_means_linear,elev,by="Genotype") #merge the dataframes

#LSmeans_LAR$elev<-LSmeans_LAR$elevation/1000
write.csv(LSmeans_LAR,file="LSmeans_LAR.csv")



#had to go in and manually remove the genos that didnt have values for all treatments, renamed the file LAR_1


LSmeans_LAR <- read.csv("LSmeans_LAR_1.csv", stringsAsFactors=FALSE)
LSmeans_LAR <-na.omit(LSmeans_LAR)

LSmeans_LAR $S_elev<-scale(LSmeans_LAR$elevation,center=TRUE, scale=TRUE)


LSmeans_LAR$Genotype<-as.factor(LSmeans_LAR$Genotype)

modC<- lmer (emmean~Treatment+S_elev*Herbivore+(1|Genotype),control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e7)), data=LSmeans_LAR)


Anova(modC)

visreg(modC,overlay=F,"S_elev", by ="Herbivore")


h_lar= ggplot(LSmeans_LAR, aes(x= elevation,y= emmean, group= Treatment, 
                               colour= Treatment))+geom_point(size=5) + scale_y_continuous("Leaf Area Herbivorized",limits =c(0, 0.15))+ scale_x_continuous("Source Elevation")  
h_lar + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(),
                           panel.grid.minor=element_blank(),legend.position = "top")+geom_smooth(method="lm",size=1.6, formula=y~x)+facet_wrap(~ Herbivore, scales="free_x") +scale_colour_manual(values = c( "lightblue","darkred"), name = "Watering treatment", labels = c("Ample water","Water-restricted"))
```


```{r, echo= FALSE}
##Gamlss models fail if there are any NA values in the entire dataset. So, I exclude NAs here
grasshopper2 <- grasshopper1[c(1,4,5,7:13,36,48:49)]
 grasshopper2 $LAR_prop14<- grasshopper2 $LAR_census14/100
 grasshopper2$elev_km<-grasshopper2 $elevation/1000
 
 grasshopper2 $trtherb<-interaction(grasshopper1 $Treatment, grasshopper2 $Herbivore,sep = "_")
 grasshopper2 $cage_block<-interaction(grasshopper1 $Cage, grasshopper2 $Block,sep = "_")
``` 
 

``` {r}
##We can proceed to the zero inflated beta regression. The issue is that these models are complicated to explain. Given that the result is nearly the same as the lmer model above, I suggest that Lisa presents the results from the lmer model      
     gamlss.model<- gamlss (formula=LAR_prop14~trtherb* elev_km+ random(cage_block)+random(Genotype),  sigma.formula=LAR_prop14~trtherb* elev_km*Herbivore+ random(cage_block)+random(Genotype), nu.formula=LAR_prop14~trtherb* elev_km*Herbivore+ random(cage_block)+random(Genotype),family=BEZI, data= grasshopper2)
      summary(gamlss.model)
      
          
visreg(gamlss.model, overlay = TRUE, "elev_km", by="trtherb", type="conditional", #scale = "response", 
       xlab="Elevation (KM)", ylab="Leaf Area Herbivorized (Scaled)", partial=TRUE,
       fill=list(col=grey
                 (c(0.99), alpha=0)
       ), band = TRUE, gg = TRUE,

       #line=list(col=grey(c(0.2,0.6))),
       points=list(cex=0.65,  pch=(19)))
      
      
```

####SLA traits


```{r}
#First, we will use ggplot to look at the data:

hist(grasshopper$SLA_rosette_2022)

SLAgg = ggplot(grasshopper, aes(x= elevation,y=SLA_rosette_2022, group= treat))+geom_point(aes(colour= treat ),size=5) +scale_x_continuous("elevation")+ scale_y_continuous("SLA")
SLAgg + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(), 
                           panel.grid.minor=element_blank())+geom_smooth(aes(colour=treat), method="glm",size=1.6)
                           
  
  


```


```{r}

#SLA:
 grasshopper $cage_block<-interaction(grasshopper $Cage, grasshopper $Block,sep = "_")
grasshopper $trtherb<-interaction(grasshopper $Treatment, grasshopper $Herbivore,sep = "_")
            
     

hist(grasshopper$SLA_rosette_2022)
  SLAgga<-ggplot(grasshopper, aes(x = Herbivore, y = SLA_rosette_2022, fill = Treatment,)) +
  geom_boxplot(outlier.shape = NA) +xlab("Herbivore treatment")+ scale_y_continuous("SLA CM3/g") +
  geom_point(pch = 21, position = position_jitterdodge())
SLAgga + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(), 
                           panel.grid.minor=element_blank(),legend.position = "top")+ scale_x_discrete(labels=c("grasshopper exclosure", "grasshopper enclosure")) +  scale_fill_manual(values = c( "lightblue","darkred"), name = "Watering treatment", labels = c("Ample water","Water-restricted"))

h_sla= ggplot(grasshopper, aes(x= elevation,y= SLA_rosette_2022, group= Treatment, 
                               colour= Treatment))+geom_point(size=5) + scale_y_continuous("SLA CM3/g")+ scale_x_continuous("Source Elevation")  
h_sla + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(),
                           panel.grid.minor=element_blank(),legend.position = "top")+geom_smooth(method="lm",size=1.6, formula=y~x)+facet_wrap(~ Herbivore, scales="free_x") +scale_colour_manual(values = c( "lightblue","darkred"), name = "Watering treatment", labels = c("Ample water","Water-restricted"))

```

```{r}

SLA<- lmer(SLA_rosette_2022 ~ Treatment+elev_km+Herbivore+S_initdiam +(1|cage_block),control = lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e7)), data = grasshopper)
Anova(SLA)
plot (SLA)

visreg(SLA, overlay = FALSE, "elev_km", by="Treatment", #type="conditional", #scale = "response", 
       xlab="Elevation (m)", ylab="Specific leaf area", partial=TRUE, cex.lab = 1.5,cex.axis = 1.5,
       fill=list(col=grey(c(0.7,0.9))),
       #line=list(col=grey(c(0,0.5))),
      # points=list(cex=1.5,col=grey(c(0.2,0.8)))
      )  



#specifying the concatenated treatment 
SLA<- lmer(SLA_rosette_2022 ~ treat*elev_km+I(elev_km^2)*treat+S_initdiam +(1|block),control = lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e7)), data = grasshopper)
Anova(SLA)
plot (SLA)

visreg(SLA, overlay = FALSE, "elev_km", by="treat", #type="conditional", #scale = "response", 
       xlab="Elevation (m)", ylab="Specific leaf area", partial=TRUE, cex.lab = 1.5,cex.axis = 1.5,
       fill=list(col=grey(c(0.7,0.9))),
       #line=list(col=grey(c(0,0.5))),
      # points=list(cex=1.5,col=grey(c(0.2,0.8)))
      )  

SLAmod <-predictorEffect("elev_km",  partial.residuals=TRUE, SLA)
  plot(SLAmod, lwd=2,xlab="Source elevation (km)", ylab="SLA", pch=19, type="response",lines=list(multiline=FALSE, lty=2:1, col="black"),
       partial.residuals=list(smooth=FALSE, pch=20, col="black"), ylim=c(0,800))


#specifying the threeway interaction
SLA2<- lmer(SLA_rosette_2022 ~ Herbivore*Treatment*elev_km+Herbivore*Treatment*I(elev_km^2)+S_initdiam +(1|block),control = lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e7)), data = grasshopper)
Anova(SLA2)
plot (SLA2)


visreg(SLA2, overlay = TRUE, "elev_km", by="Treatment", #type="conditional", #scale = "response", 
       xlab="Elevation (m)", ylab="Specific leaf area", partial=TRUE, cex.lab = 1.5,cex.axis = 1.5,
       fill=list(col=grey(c(0.7,0.9))),
       #line=list(col=grey(c(0,0.5))),
      # points=list(cex=1.5,col=grey(c(0.2,0.8)))
      )  

SLAmod2 <-predictorEffect("elev_km",  partial.residuals=TRUE, SLA2)
  plot(SLAmod2, lwd=2,xlab="Source elevation (km)", ylab="SLA cm3/g", pch=19, type="response",lines=list(multiline=TRUE, lty=2:1, col="black"),
       partial.residuals=list(smooth=FALSE, pch=20, col="black"), ylim=c(0,650))

  
  
SLA2<- lm(SLA_rosette_2022 ~ Herbivore+Treatment+elev_km+S_initdiam, data = grasshopper)
Anova(SLA2)
plot (SLA2)

library(rstatix)

#descriptive and visual look at variable
parents1 <- grasshopper %>% 
  group_by(treat) %>%
  get_summary_stats(SLA_rosette_2022, type="mean_se")
parents1

#plasticity figure
ggplot(
  grasshopper,
  aes(x=treat, y=LAR_census14_2022, color = elevation)) + # Change fill to color
  theme_classic(base_size = 22) + 
  #geom_point() + 
  stat_summary(fun=mean, position = "dodge") + 
  stat_summary(
    geom="errorbar", 
    fun.data= mean_cl_boot,
    width = 0.1, size = 0.2, col = "Black"
    ) + 
  # Lines by species using grouping
  #scale_color_viridis(discrete = FALSE) +
  #scale_fill_manual(values = cbp2)+
  #stat_summary(aes(group = elevation), geom = "line", size=1.5, fun = mean) +
  ylab("Specific Leaf Area") +
  xlab("Maternal enviornment")

```






```{r}
#specifying the concatenated treatment 
SLA<- lmer(SLA_rosette_2022 ~ treat+S_initdiam +(1|block),control = lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e7)), data = grasshopper)
Anova(SLA)
plot (SLA)

visreg(SLA, "treat", #type="conditional", #scale = "response", 
       xlab="Elevation (m)", ylab="Specific leaf area", partial=TRUE, cex.lab = 1.5,cex.axis = 1.5,
       fill=list(col=grey(c(0.7,0.9))),
       #line=list(col=grey(c(0,0.5))),
      # points=list(cex=1.5,col=grey(c(0.2,0.8)))
      ) 


```

LWC
```{r}
#First, we will use ggplot to look at the data:

hist(grasshopper$lwc_rosette_2022)

SLAgg = ggplot(grasshopper, aes(x= elevation,y=lwc_rosette_2022, group= treat))+geom_point(aes(colour= treat ),size=5) +scale_x_continuous("elevation")+ scale_y_continuous("LWC")
SLAgg + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(), 
                           panel.grid.minor=element_blank())+geom_smooth(aes(colour=treat), method="glm",size=1.6)
                           
  
  
  SLAgga<-ggplot(grasshopper, aes(x = Herbivore, y = lwc_rosette_2022, fill = Treatment,)) +
  geom_boxplot(outlier.shape = NA) +xlab("Herbivore treatment")+ scale_y_continuous("LWC g/cm3") +
  geom_point(pch = 21, position = position_jitterdodge())
SLAgga + theme_bw() + theme(text = element_text(size=20),axis.line.x = element_line(colour = "black"), 
                           axis.line.y = element_line(colour = "black"), panel.border = element_blank(), panel.grid.major =element_blank(), 
                           panel.grid.minor=element_blank(),legend.position = "top")+ scale_x_discrete(labels=c("grasshopper exclosure", "grasshopper enclosure")) +  scale_fill_manual(values = c( "lightblue","darkred"), name = "Watering treatment", labels = c("Ample water","Water-restricted"))


```


```{r}
#specifying the concatenated treatment 
LWC<- lmer(lwc_rosette_2022 ~ treat*elev_km+#I(elev_km^2)*treat
             +S_initdiam +(1|block),control = lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e7)), data = grasshopper)
Anova(LWC)
plot (LWC)

visreg(LWC, overlay = FALSE, "elev_km", by="treat", #type="conditional", #scale = "response", 
       xlab="Elevation (m)", ylab="LWC", partial=TRUE, cex.lab = 1.5,cex.axis = 1.5,
       fill=list(col=grey(c(0.7,0.9))),
       #line=list(col=grey(c(0,0.5))),
      # points=list(cex=1.5,col=grey(c(0.2,0.8)))
      )  

lwcmod <-predictorEffect("elev_km",  partial.residuals=TRUE, LWC)
  plot(lwcmod, lwd=2,xlab="Source elevation (km)", ylab="LWC", pch=19, type="response",lines=list(multiline=FALSE, lty=2:1, col="black"),
       partial.residuals=list(smooth=FALSE, pch=20, col="black"), ylim=c(0,1))


#specifying the threeway interaction
lwc2<- lmer(lwc_rosette_2022 ~ Herbivore*Treatment*elev_km+S_initdiam +(1|block),control = lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e7)), data = grasshopper)
Anova(lwc2)
plot (lwc2)


visreg(lwc2, overlay = TRUE, "elev_km", by="Treatment", #type="conditional", #scale = "response", 
       xlab="Elevation (m)", ylab="LWC", partial=TRUE, cex.lab = 1.5,cex.axis = 1.5,
       fill=list(col=grey(c(0.7,0.9))),
       #line=list(col=grey(c(0,0.5))),
      # points=list(cex=1.5,col=grey(c(0.2,0.8)))
      )  

lwcmod2 <-predictorEffect("elev_km",  partial.residuals=TRUE, lwc2)
  plot(lwcmod2, lwd=2,xlab="Source elevation (km)", ylab="LWC", pch=19, type="response",lines=list(multiline=TRUE, lty=2:1, col="black"),
       partial.residuals=list(smooth=FALSE, pch=20, col="black"), ylim=c(0,1))




```


